// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users_sql

type User struct {
	ID        int32  `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Dob       string `json:"dob"`
}
