// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package posts_sql

import (
	"database/sql"
)

type Post struct {
	ID      int32          `json:"id"`
	OwnerID int32          `json:"ownerId"`
	Body    string         `json:"body"`
	MediaID sql.NullString `json:"mediaId"`
}
